In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("customer_shopping_behavior.csv")
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [5]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [6]:
df["Review Rating"]=df.groupby("Category")["Review Rating"].transform(lambda x:x.fillna(x.median()))

In [7]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(" ","_")

In [8]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [9]:
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [10]:
lable=['young_Adult','Adult','Mid_Age','Old']
df['Age_Group']=pd.qcut(df['age'],4,labels=lable)
df['Age_Group']

0           Mid_Age
1       young_Adult
2           Mid_Age
3       young_Adult
4           Mid_Age
           ...
3895          Adult
3896        Mid_Age
3897        Mid_Age
3898          Adult
3899        Mid_Age
Name: Age_Group, Length: 3900, dtype: category
Categories (4, object): ['young_Adult' < 'Adult' < 'Mid_Age' < 'Old']

In [11]:
df['frequency_of_purchases'].unique()
frequency_mapping={
    'Weekly':7,
    'Fortnightly':14,
    "Annually":365,
    'Quarterly':90,
    "Bi-Weekly":14,
    'Monthly':30,
    'Every 3 Months':90
}
df['purchase_freq']=df['frequency_of_purchases'].map(frequency_mapping)
df[['purchase_freq','frequency_of_purchases']]

      purchase_freq frequency_of_purchases
0                14            Fortnightly
1                14            Fortnightly
2                 7                 Weekly
3                 7                 Weekly
4               365               Annually
...             ...                    ...
3895              7                 Weekly
3896             14              Bi-Weekly
3897             90              Quarterly
3898              7                 Weekly
3899             90              Quarterly

[3900 rows x 2 columns]

In [12]:
# df[['discount_applied','promo_code_used'
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [13]:
df.drop('promo_code_used',axis=1,inplace=True)

In [14]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'Age_Group', 'purchase_freq'],
      dtype='object')

In [15]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\reash\anaconda3\lib\site-packages (9.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
pip install sqlalchmy

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement sqlalchmy (from versions: none)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for sqlalchmy

In [17]:
pip install pymysql

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [18]:
import mysql.connector
from sqlalchemy import create_engine

In [22]:
engine = create_engine(
    "mysql+pymysql://root:KATOCHshaab%401@localhost:3306/customer_behaviour"
)

df.to_sql("cleaned_dataset", con=engine, if_exists="replace", index=False)

print("Data uploaded successfully!")

Data uploaded successfully!

In [25]:
df['subscription_status'].unique()

array(['Yes', 'No'], dtype=object)